### ISSUE TITLE
Problem wrapping the environment

### ISSUE THREAD

**Issue by l4nz8** [l4nz8/q_play#1]
Traceback (most recent call last):
  File "../q_play/baseline/main.py", line 37, in <module>
    state = env.reset()
  File "../python3.10/site-packages/gym/wrappers/frame_stack.py", line 186, in reset
    obs, info = self.env.reset(**kwargs)
  File "../python3.10/site-packages/gym/wrappers/normalize.py", line 84, in reset
    obs, info = self.env.reset(**kwargs)
  File "../python3.10/site-packages/gym/core.py", line 379, in reset
    obs, info = self.env.reset(**kwargs)
ValueError: too many values to unpack (expected 2)

i used the example from the [mario rl tutorial](https://pytorch.org/tutorials/intermediate/mario_rl_tutorial.html) and tried to customize the game environment but i have the problem that when wrapping the environment too many values are returned. I could trace the problem back to line 26 in main.py `env = PyBoyGymEnv(pyboy, observation_type='raw', action_type='toggle', simultaneous_actions=False)` where the environment is initialized, but I have no idea how to solve this problem.

**Comment by l4nz8** [comment]
done
